/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-07 18:49:21
*/

package com.silvera.SciPaper.service.base;

import org.springframework.stereotype.Service;
import com.silvera.SciPaper.domain.model.*;
import com.silvera.SciPaper.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface ISciPaperService {

    // Auto-generated CRUD methods
    
    
    
    public SciPaper createSciPaper(SciPaper scipaper);
    
    
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate);
    
    
    public SciPaper readSciPaper(java.lang.String id);
    
    
    public void deleteSciPaper(java.lang.String id);
    
    
    
    
    public Section createSection(Section section);
    
    
    public Section updateSection(java.lang.String id, Section sectionUpdate);
    
    
    public Section readSection(java.lang.String id);
    
    
    public void deleteSection(java.lang.String id);
    
    

    
    public SciPaper uploadSciPaper(java.lang.String username, UploadPaperDto dto);
    
    public java.util.List<SciPaper> getAll();
    
    public SciPaper getOne(java.lang.String id);
    
    public void publishPaper(SciPaper sciPaper);
    

    

}