/**
 * THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!
 * <p>
 * Generated by: silvera
 * Date: 2022-05-07 18:49:21
 */

package com.silvera.User.controller;

import com.silvera.User.domain.model.LoginDto;
import com.silvera.User.domain.model.User;
import com.silvera.User.service.base.IUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;


@RefreshScope
@RestController
public class UserController {

    @Autowired
    IUserService userService;

    // Auto-generated CRUD methods


    @RequestMapping(value = "/user", method = RequestMethod.POST)
    @ResponseBody
    public User createUser(@Valid @RequestBody User user) {
        return userService.createUser(user);
    }


    @RequestMapping(value = "/user/{id}", method = RequestMethod.PUT)
    @ResponseBody
    public User updateUser(@PathVariable java.lang.String id, @Valid @RequestBody User user) {
        return userService.updateUser(id, user);
    }


    @RequestMapping(value = "/user/{id}", method = RequestMethod.GET)
    @ResponseBody
    public User readUser(@PathVariable java.lang.String id) {
        return userService.readUser(id);
    }


    @RequestMapping(value = "/user/{id}", method = RequestMethod.DELETE)
    @ResponseBody
    public void deleteUser(@PathVariable java.lang.String id) {
        userService.deleteUser(id);
    }


    @PostMapping(value = "register")


    @ResponseBody
    public User register(@RequestBody User user) {

        return userService.register(user);

    }


    @PostMapping(value = "login")


    @ResponseBody
    public User login(@RequestBody LoginDto loginDto) {

        return userService.login(loginDto);

    }


    @PostMapping(value = "logout/{username}")


    @ResponseBody
    public void logout(@PathVariable java.lang.String username) {

        userService.logout(username);

    }


    @GetMapping(value = "/")


    @ResponseBody
    public java.util.List<User> getAllUsers() {

        return userService.getAllUsers();

    }


    @GetMapping(value = "/is-logged-in/{username}")


    @ResponseBody
    public java.lang.Boolean isLoggedIn(@PathVariable java.lang.String username) {

        return userService.isLoggedIn(username);

    }


    @GetMapping(value = "/get-name/{username}")


    @ResponseBody
    public java.lang.String getName(@PathVariable java.lang.String username) {

        return userService.getName(username);

    }


}