server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: SCI-PAPER-SERVICE
          uri: lb://SCI-PAPER-SERVICE
          predicates:
            - Path=/scipaper/**
        - id: LIBRARY-SERVICE
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
